name: nyc-taxi-pipelines
schedule: monthly
start_date: "2021-01-01"

default_connections:
  duckdb: "duckdb-nyc-taxi"

variables:
  taxi_types:
    type: array
    items:
      type: string
    default: ["yellow", "green"]